"""
CryptoDept Project Collector v5.0 — TOKEN-OPTIMIZED
====================================================
Максимална token efficiency. Премахва всичко излишно.

Основни цели:
- 50-70% по-малко токени от v4
- Само КОД и КОНФИГУРАЦИЯ
- Без излишни visual elements
- Без emoji-rich tree
- Без декорация (=, ―, ★)
- Без duplicate paths

Режими:
  python collect_cryptodept.py            # Default: smart (recommended)
  python collect_cryptodept.py smart      # Само relevant файлове, compact format
  python collect_cryptodept.py skeleton   # Само структура (~5K tokens)
  python collect_cryptodept.py code       # Код само, без xml/json (~50% от smart)
  python collect_cryptodept.py full       # ВСИЧКО (legacy v4 behavior)

Изпълнение:
  cd D:\\
  python collect_cryptodept.py
  → CryptoDept_DUMP.txt в същата директория
"""

import os
import sys
import re
from pathlib import Path
from datetime import datetime
from collections import defaultdict

# ==========================================================
# КОНФИГУРАЦИЯ
# ==========================================================

ROOT_DIR = r"D:\CryptoDept"
OUTPUT_DIR = "."
PROJECT_NAME = "CryptoDept"

# Maximum file content per file (override)
MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024

# Token-saving: strip коментари от Kotlin файлове
STRIP_COMMENTS_FROM_KOTLIN = True

# Token-saving: max consecutive празни линии
MAX_BLANK_LINES = 1


# ==========================================================
# КОИ ФАЙЛОВЕ ДА ВКЛЮЧВАМЕ
# ==========================================================

# Code files (винаги включваме)
CODE_EXTENSIONS = {
    ".kt", ".kts", ".java"
}

# Config files (включваме selectively)
CONFIG_EXTENSIONS = {
    ".gradle", ".pro", ".properties", ".toml"
}

# Resource files (включваме само important)
RESOURCE_EXTENSIONS = {
    ".xml"
}

# Markdown / Documentation (включваме само root-level)
DOC_EXTENSIONS = {
    ".md", ".txt"
}

# ВСИЧКИ останали → SKIP


# ==========================================================
# КОИ ДИРЕКТОРИИ ДА ПРОПУСКАМЕ (винаги)
# ==========================================================

SKIP_DIRS = {
    # Build artifacts
    "build", ".gradle", ".idea", ".kotlin", "gradle",
    # Version control
    ".git", ".github",
    # Node / web
    "node_modules", ".cache", "dist", "out",
    # Test / coverage
    ".pytest_cache", "__pycache__", "coverage",
    # Generated
    "generated", "intermediates", "outputs",
    # Schemas (these are auto-generated by Room)
    "schemas",
    # Misc
    "captures", ".externalNativeBuild", ".cxx",
}


# ==========================================================
# КОИ ПЪТИЩА ДА ПРОПУСКАМЕ (winapp specific)
# ==========================================================

SKIP_PATH_PATTERNS = [
    # Build outputs
    r"\\build\\",
    r"/build/",
    # IDE
    r"\\.idea\\",
    r"\\.gradle\\",
    # Tests outputs (запазваме source тестове, но не reports)
    r"reports[\\/]",
    r"test-results[\\/]",
    # Native build
    r"\\.cxx",
    # Кеш
    r"\\.kotlin\\",
]


# ==========================================================
# КОИ ФАЙЛОВЕ ДА ПРОПУСКАМЕ (file-level)
# ==========================================================

SKIP_FILE_NAMES = {
    # CRITICAL: Never include local.properties (contains API keys!)
    "local.properties",
    # Lock files (autoexpansion)
    "package-lock.json", "yarn.lock", "Cargo.lock",
    "gradle-wrapper.jar", "gradle-wrapper.properties",
    "gradlew", "gradlew.bat",
    # Logs / temp
    ".DS_Store", "Thumbs.db", "desktop.ini",
    # Generated
    "google-services.json",  # auto-generated by Firebase
    # Old dumps от мен
    "CryptoDept_DUMP.txt",
    "CryptoDept_DUMP_FULL.txt",
    "CryptoDept_DUMP_SKELETON.txt",
    "CryptoDept_DUMP_CRITICAL.txt",
    "CryptoDept_DUMP_PROGRESS.txt",
    "project_summary.txt",
    # Old python scripts
    "collect_project.py",
    "collect_project_v2.py",
    "collect_project_v3.py",
    "collect_cryptodept.py",
    "extract_app.py",
}

# Skip files starting with these prefixes
SKIP_FILE_PREFIXES = {
    "CryptoDept_DUMP",
    "project_summary",
}

# Skip files matching these patterns
SKIP_FILE_PATTERNS = [
    r".*\.bak$",
    r".*\.tmp$",
    r".*\.swp$",
    r".*~$",
]


# ==========================================================
# ВАЖНИ ФАЙЛОВЕ ЗА КОНКРЕТНИ MODE-ове
# ==========================================================

# В skeleton mode — само тези файлове + structure
SKELETON_INCLUDE_FILES = {
    "build.gradle.kts",  # root + app
    "libs.versions.toml",
    "settings.gradle.kts",
    "AndroidManifest.xml",
    "AGENTS.MD",
    "AGENTS.md",
    "agents.md",
    "README.md",
    "PRICES.md",
    "Privacy Policy.txt",
    "delete account.txt",
}

# Critical CryptoDept файлове (винаги да присъстват)
CRITICAL_FILES = {
    "build.gradle.kts",
    "libs.versions.toml",
    "AndroidManifest.xml",
    "proguard-rules.pro",
    "AGENTS.MD",
    "README.md",
}


# ==========================================================
# SECRET SCANNER PATTERNS
# ==========================================================

SECRET_PATTERNS = [
    (r"sk-ant-[A-Za-z0-9_-]{20,}", "Anthropic API key"),
    (r"sk-[A-Za-z0-9]{40,}", "OpenAI API key"),
    (r"AIza[0-9A-Za-z_-]{35}", "Google API key (Gemini/Firebase)"),
    # Note: Etherscan/Helius use hex strings — easy false positives.
    # Skip generic hex patterns to avoid Matrix Rain false positives.
]


# ==========================================================
# ARCHITECTURE LAYER CLASSIFIER
# ==========================================================

def classify_layer(rel_path: str) -> str:
    """Classify file by architecture layer (for stats only)."""
    p = rel_path.replace("\\", "/").lower()

    if "/build/" in p or "/.gradle/" in p:
        return None  # skip

    # Build / config
    if rel_path.endswith((".gradle", ".gradle.kts", ".pro", ".properties", ".toml")):
        return "build"

    # Tests
    if "/test/" in p:
        return "tests-unit"
    if "/androidtest/" in p:
        return "tests-android"

    # Architecture layers (Kotlin specific)
    if "/data/api/" in p:
        return "data-api"
    if "/data/db/" in p or "/data/dao/" in p or "/data/entity/" in p:
        return "data-db"
    if "/data/repository/" in p or "repositoryimpl" in p:
        return "data-repo"
    if "/data/" in p:
        return "data-other"
    if "/domain/model/" in p:
        return "domain-models"
    if "/domain/repository/" in p:
        return "domain-repo-interface"
    if "/domain/usecase/" in p:
        return "domain-usecase"
    if "/domain/" in p:
        return "domain-other"
    if "/di/" in p:
        return "di"
    if "/ui/" in p:
        return "ui"
    if "/viewmodel/" in p:
        return "viewmodel"
    if "/service/" in p:
        return "service"
    if "/widget/" in p:
        return "widget"
    if "/util/" in p or "/utility/" in p:
        return "util"

    # Resources
    if "/res/values/strings.xml" in p:
        return "strings"
    if "/res/" in p:
        return "resources"

    # Docs
    if rel_path.endswith(".md") or rel_path.endswith(".txt"):
        return "docs"

    return "other"


# ==========================================================
# CONTENT PROCESSING (token-saving)
# ==========================================================

KOTLIN_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
KOTLIN_LINE_COMMENT = re.compile(r"//[^\n]*")
KDOC_BLOCK = re.compile(r"/\*\*.*?\*/", re.DOTALL)
MULTI_BLANK = re.compile(r"\n\s*\n\s*\n+")


def strip_kotlin_comments(content: str) -> str:
    """Remove block + line comments to save tokens. Keeps annotations."""
    # Запазваме KDoc (/** ... */) защото съдържат semantic info
    # но премахваме обикновени блокови коментари /* ... */ и // line
    
    lines = content.split("\n")
    output_lines = []
    in_block_comment = False
    
    for line in lines:
        # Skip целия line ако е само comment
        stripped = line.strip()
        
        # Skip празни comments като "// "
        if stripped.startswith("// ") and len(stripped) <= 3:
            continue
        if stripped == "//":
            continue
            
        # Detect start/end of block comment
        if "/*" in line and "*/" not in line:
            in_block_comment = True
            continue
        if in_block_comment:
            if "*/" in line:
                in_block_comment = False
            continue
            
        # Remove inline // comments (but keep URLs like https://)
        # Simple heuristic: if "//" не е в start of line и предходният char не е ":"
        if "//" in line:
            idx = line.find("//")
            # Check if preceded by ":" (URL)
            if idx > 0 and line[idx - 1] == ":":
                pass  # keep
            else:
                line = line[:idx].rstrip()
                if not line.strip():
                    continue
                    
        output_lines.append(line)
    
    result = "\n".join(output_lines)
    
    # Collapse multiple blank lines
    result = MULTI_BLANK.sub("\n\n", result)
    
    return result


def compact_whitespace(content: str) -> str:
    """Reduce excessive whitespace."""
    return MULTI_BLANK.sub("\n\n", content)


def process_content(content: str, file_path: str) -> str:
    """Apply token-saving transformations based on file type."""
    if not STRIP_COMMENTS_FROM_KOTLIN:
        return content
    
    if file_path.endswith((".kt", ".kts", ".java")):
        return strip_kotlin_comments(content)
    
    # For all other files: just compact whitespace
    return compact_whitespace(content)


# ==========================================================
# FILE FILTERING
# ==========================================================

def should_skip_dir(dir_name: str) -> bool:
    return dir_name in SKIP_DIRS


def should_skip_path(path: str) -> bool:
    for pattern in SKIP_PATH_PATTERNS:
        if re.search(pattern, path):
            return True
    return False


def should_skip_file(file_path: str, mode: str = "smart") -> bool:
    """Determine if file should be skipped based on mode."""
    name = os.path.basename(file_path)
    
    # Always skip these
    if name in SKIP_FILE_NAMES:
        return True
    
    for prefix in SKIP_FILE_PREFIXES:
        if name.startswith(prefix):
            return True
    
    for pattern in SKIP_FILE_PATTERNS:
        if re.match(pattern, name):
            return True
    
    ext = os.path.splitext(name)[1].lower()
    
    # In code mode → only kotlin/java
    if mode == "code":
        return ext not in CODE_EXTENSIONS
    
    # In smart mode → code + selected configs + AndroidManifest
    if mode == "smart":
        # Include all .kt/.java
        if ext in CODE_EXTENSIONS:
            return False
        # Include build config files
        if ext in CONFIG_EXTENSIONS:
            return False
        # Include only IMPORTANT xml files
        if ext == ".xml":
            # Manifest is critical
            if name == "AndroidManifest.xml":
                return False
            # strings.xml gets included (translations)
            if name == "strings.xml":
                return False
            # Skip themes, colors, layout, drawables, animations
            return True
        # Include only root-level .md files
        if ext in DOC_EXTENSIONS:
            # Get parent dir
            parent = os.path.dirname(file_path)
            # Allow if in root or docs/ folder
            if parent == ROOT_DIR or os.path.basename(parent) == "docs":
                return False
            return True
        return True
    
    # In full mode → almost everything
    if mode == "full":
        # Skip binary types
        skip_bin = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".ico",
                    ".ttf", ".otf", ".woff", ".woff2",
                    ".mp3", ".mp4", ".wav", ".ogg",
                    ".jar", ".aar", ".zip", ".apk", ".aab",
                    ".so", ".dll", ".dylib",
                    ".class", ".dex"}
        return ext in skip_bin
    
    # Skeleton mode → almost everything skipped
    if mode == "skeleton":
        return name not in SKELETON_INCLUDE_FILES
    
    return False


# ==========================================================
# SECRET SCANNER
# ==========================================================

def scan_for_secrets(content: str, rel_path: str) -> list:
    """Return list of (description, snippet) for suspicious patterns."""
    findings = []
    
    # Skip Matrix Rain (animation alphabet — false positive)
    if "MatrixRainScreen" in rel_path:
        return findings
    
    for pattern, description in SECRET_PATTERNS:
        matches = re.findall(pattern, content)
        for match in matches:
            # Truncate for safety
            snippet = match[:20] + "..." if len(match) > 20 else match
            findings.append((description, snippet))
    
    return findings


# ==========================================================
# MAIN COLLECTION
# ==========================================================

def collect_files(mode: str) -> tuple:
    """
    Walk filesystem and collect files matching criteria.
    Returns (files_data, stats, secrets).
    """
    files_data = []  # list of (rel_path, content, size_bytes)
    stats = defaultdict(lambda: {"count": 0, "bytes": 0})
    secrets = []
    
    root = Path(ROOT_DIR)
    if not root.exists():
        print(f"ERROR: {ROOT_DIR} does not exist!")
        sys.exit(1)
    
    for current_path, dirs, files in os.walk(ROOT_DIR):
        # Filter directories in place
        dirs[:] = [d for d in dirs if not should_skip_dir(d)]
        
        # Skip path if matches skip patterns
        if should_skip_path(current_path):
            continue
        
        for filename in files:
            full_path = os.path.join(current_path, filename)
            rel_path = os.path.relpath(full_path, ROOT_DIR)
            
            # Apply file-level filtering
            if should_skip_file(full_path, mode):
                continue
            
            # Check file size
            try:
                file_size = os.path.getsize(full_path)
                if file_size > MAX_FILE_SIZE_BYTES:
                    continue
                if file_size == 0:
                    continue  # skip empty files
            except OSError:
                continue
            
            # Read content
            try:
                with open(full_path, "r", encoding="utf-8") as f:
                    content = f.read()
            except (UnicodeDecodeError, OSError):
                # Try latin-1 as fallback
                try:
                    with open(full_path, "r", encoding="latin-1") as f:
                        content = f.read()
                except OSError:
                    continue
            
            # Apply token-saving transformations
            processed = process_content(content, full_path)
            
            # Scan for secrets
            file_secrets = scan_for_secrets(content, rel_path)
            for desc, snippet in file_secrets:
                secrets.append((rel_path, desc, snippet))
            
            # Classify layer
            layer = classify_layer(rel_path)
            if layer:
                stats[layer]["count"] += 1
                stats[layer]["bytes"] += len(processed.encode("utf-8"))
            
            files_data.append((rel_path, processed, len(processed.encode("utf-8"))))
    
    return files_data, stats, secrets


# ==========================================================
# OUTPUT WRITER (token-optimized format)
# ==========================================================

def write_output(mode: str, files_data: list, stats: dict, secrets: list):
    """Write compact, token-optimized output."""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out_path = os.path.join(OUTPUT_DIR, f"{PROJECT_NAME}_DUMP.txt")
    
    # Sort files: critical first, then by layer, then alphabetically
    def sort_key(item):
        rel_path, _, _ = item
        name = os.path.basename(rel_path)
        # Critical files first
        if name in CRITICAL_FILES:
            return (0, rel_path)
        return (1, rel_path)
    
    files_data.sort(key=sort_key)
    
    total_files = len(files_data)
    total_bytes = sum(size for _, _, size in files_data)
    
    with open(out_path, "w", encoding="utf-8") as f:
        # ============ HEADER ============
        f.write(f"# {PROJECT_NAME} DUMP — {mode.upper()} MODE\n")
        f.write(f"# Generated: {timestamp}\n")
        f.write(f"# Root: {ROOT_DIR}\n")
        f.write(f"# Files: {total_files}\n")
        f.write(f"# Size: {total_bytes / 1024:.1f} KB\n")
        f.write("\n")
        
        # ============ LAYER STATS ============
        f.write("## LAYERS\n")
        for layer_name in sorted(stats.keys()):
            data = stats[layer_name]
            f.write(f"  {layer_name:20s} {data['count']:4d} files  {data['bytes'] / 1024:.1f} KB\n")
        f.write("\n")
        
        # ============ SECRETS ============
        if secrets:
            f.write("## SECRETS DETECTED\n")
            for rel_path, desc, snippet in secrets:
                f.write(f"  {rel_path}  →  {desc}: {snippet}\n")
            f.write("\n")
        
        # ============ FILES ============
        f.write("## FILES\n\n")
        
        for rel_path, content, size in files_data:
            # Compact file header: just path + size
            normalized_path = rel_path.replace("\\", "/")
            f.write(f"### {normalized_path}\n")
            f.write("```\n")
            f.write(content)
            if not content.endswith("\n"):
                f.write("\n")
            f.write("```\n\n")
    
    return out_path, total_files, total_bytes


# ==========================================================
# MAIN
# ==========================================================

def main():
    mode = "smart"
    if len(sys.argv) > 1:
        mode = sys.argv[1].lower()
        if mode not in ("smart", "skeleton", "code", "full"):
            print(f"Unknown mode: {mode}")
            print("Available: smart, skeleton, code, full")
            sys.exit(1)
    
    print(f"CryptoDept Collector v5 — mode: {mode}")
    print(f"Source: {ROOT_DIR}")
    print(f"Strip comments: {STRIP_COMMENTS_FROM_KOTLIN}")
    print("Scanning...")
    
    files_data, stats, secrets = collect_files(mode)
    
    if not files_data:
        print("ERROR: No files collected!")
        sys.exit(1)
    
    out_path, total_files, total_bytes = write_output(mode, files_data, stats, secrets)
    
    print(f"\nDone!")
    print(f"Output: {out_path}")
    print(f"Files: {total_files}")
    print(f"Size: {total_bytes / 1024:.1f} KB ({total_bytes / 1024 / 1024:.2f} MB)")
    
    # Estimate tokens (rough: ~4 chars per token)
    estimated_tokens = total_bytes / 4
    print(f"Estimated tokens: ~{estimated_tokens / 1000:.1f}K")
    
    if secrets:
        print(f"\nWARNING: {len(secrets)} potential secrets detected — review output!")


if __name__ == "__main__":
    main()