COINGECKO_API_KEY=CG-1hQirU43avDQup1FrLcyJKgR
BINANCE_API_KEY=slKqBMCCYIBLAi4TABLtr7jaM7MaPPA1JbraMRr0MGrf3QaEsXy6OhCDV3YY4AQi
ETHERSCAN_API_KEY=2UCS225WI9E8MDS7G3Y6ZFBI6VMJVS7TNE
COINGLASS_API_KEY=59d6e40e3ffa44388e6b05513652451a
ALPHA_VANTAGE_API_KEY=7UVKRB827GT9S78Y
COINMARKETCAL_API_KEY=nP3LEJAv4xaNhvNQJvikx7y5ZOiIHRRz7TcxyBaa
GEMINI_API_KEY=AIzaSyANLj0EIzWVzpjY-Yslzu2UC5WXKv_IjIY
CRYPTOPANIC_API_KEY=