package com.cryptodept.domain.tier

/**
 * Central registry of all features that can be gated by tier.
 * Single source of truth for the entire terminal.
 */
enum class FeatureKey(
    val requiredTier: AccessTier,
    val displayName: String,
    val description: String,
) {
    
    // 🆓 FREE TIER FEATURES
    
    DASHBOARD_PRICE_TICKER(
        requiredTier = AccessTier.FREE,
        displayName = "Market Ticker",
        description = "A real-time high-fidelity ticker of the top 10 most relevant cryptocurrencies. Displays live pricing, 24-hour delta, and instant access to technical charts.",
    ),
    DASHBOARD_AI_PULSE_SHORT(
        requiredTier = AccessTier.FREE,
        displayName = "AI Market Pulse",
        description = "A condensed intelligence summary generated by our sub-agent orchestrator. Perfect for a 10-second situational awareness check.",
    ),
    DASHBOARD_TODAYS_MOVERS(
        requiredTier = AccessTier.FREE,
        displayName = "Volatility Scanner",
        description = "Identifies high-impact assets with the most significant price expansion or contraction in the last 24 hours.",
    ),
    DASHBOARD_WHALE_INSIGHT(
        requiredTier = AccessTier.FREE,
        displayName = "Whale Flow Signal",
        description = "A processed indicator derived from raw on-chain movements. Tracks capital flow between wallets and exchanges.",
    ),
    DASHBOARD_SENTIMENT_GAUGE(
        requiredTier = AccessTier.FREE,
        displayName = "Fear & Greed Index",
        description = "A multi-factor psychological barometer based on volatility, volume, and social media dominance.",
    ),
    DASHBOARD_NETWORK_HEALTH_BASIC(
        requiredTier = AccessTier.FREE,
        displayName = "Network Health (Basic)",
        description = "Real-time metrics for Bitcoin and Ethereum network layers, including gas fees and mempool congestion.",
    ),
    DASHBOARD_AGENT_STATUS_MINIMAL(
        requiredTier = AccessTier.FREE,
        displayName = "Agent Status Row",
        description = "Visual indicators showing which specialized AI agents are currently active and scanning.",
    ),
    MARKETS_TOP_50(
        requiredTier = AccessTier.FREE,
        displayName = "Standard Liquidity Index",
        description = "Access to the top 50 cryptocurrencies by market capitalization. Covers the most liquid and reliable assets.",
    ),
    COIN_DETAIL_BASIC(
        requiredTier = AccessTier.FREE,
        displayName = "Coin Details",
        description = "Core statistical data for any supported cryptocurrency: valuation, supply, and fundamental info.",
    ),
    NEWS_FEED(
        requiredTier = AccessTier.FREE,
        displayName = "News Feed",
        description = "An aggregated stream of the most relevant crypto news, filtered to eliminate clickbait.",
    ),
    POSITION_SIZER(
        requiredTier = AccessTier.FREE,
        displayName = "Risk Architect",
        description = "Calculate the exact dollar amount and coin quantity you should risk based on your account size and stop-loss.",
    ),
    TRADE_PLANNER_BASIC(
        requiredTier = AccessTier.FREE,
        displayName = "Pre-Trade Validator",
        description = "A professional checklist for Entry, Stop-Loss, and Take-Profit levels. Validates Risk:Reward ratio.",
    ),
    FEAR_GREED_DASHBOARD(
        requiredTier = AccessTier.FREE,
        displayName = "Sentiment Dashboard",
        description = "A full deep-dive into historical fear and greed trends to identify cyclical bottoms and tops.",
    ),
    DAILY_AI_PICK(
        requiredTier = AccessTier.FREE,
        displayName = "Daily AI Pick",
        description = "One algorithmic prediction per 24 hours, rotating between the top 10 assets. Provides entry zones and targets.",
    ),
    GLOSSARY(
        requiredTier = AccessTier.FREE,
        displayName = "Crypto Intelligence Database",
        description = "A comprehensive deep-dive into technical terms, on-chain metrics, and institutional trading strategies.",
    ),
    FEATURE_HELP(
        requiredTier = AccessTier.FREE,
        displayName = "System Help Protocols",
        description = "Contextual documentation available for every module within the CryptoDept terminal.",
    ),
    SETTINGS_BASIC(
        requiredTier = AccessTier.FREE,
        displayName = "Terminal Configuration",
        description = "Full control over theme, phosphor modes, audio feedback, and notification protocols.",
    ),
    ALERTS_LIMITED_3(
        requiredTier = AccessTier.FREE,
        displayName = "Standard Alerts",
        description = "Basic price monitoring. FREE users can maintain up to 3 active alerts simultaneously.",
    ),
    WATCHLIST_SINGLE(
        requiredTier = AccessTier.FREE,
        displayName = "Primary Tracker",
        description = "A localized watchlist for focused monitoring. Tracks up to 3 high-priority assets on the dashboard.",
    ),
    ONBOARDING_TOUR(
        requiredTier = AccessTier.FREE,
        displayName = "Tactical Training",
        description = "The interactive multi-step walkthrough of all CryptoDept terminal subsystems.",
    ),

    // 💎 PRO TIER FEATURES
    
    DASHBOARD_AI_NARRATIVE_FULL(
        requiredTier = AccessTier.PRO,
        displayName = "Elite AI Narrative",
        description = "Unlocks the full streaming context from our Reasoning Orchestrator. Deep technical and macro confluence.",
    ),
    DASHBOARD_WHALE_FEED_LIVE(
        requiredTier = AccessTier.PRO,
        displayName = "Live On-Chain Feed",
        description = "The raw, unfiltered heartbeat of institutional capital. Capture moves over $500,000 in real-time.",
    ),
    DASHBOARD_SENTIMENT_MATRIX(
        requiredTier = AccessTier.PRO,
        displayName = "Sentiment Matrix",
        description = "Correlates social dominance with price action across multiple assets to identify irrationality.",
    ),
    MARKETS_TOP_200(
        requiredTier = AccessTier.PRO,
        displayName = "Global Market Intelligence",
        description = "Extended coverage of the top 200 cryptocurrencies. Dive into mid-cap and small-cap opportunities.",
    ),
    WATCHLISTS_UNLIMITED(
        requiredTier = AccessTier.PRO,
        displayName = "Command Watchlists",
        description = "Create unlimited custom watchlists and track up to 30 coins simultaneously.",
    ),
    MARKETS_FILTERS(
        requiredTier = AccessTier.PRO,
        displayName = "Advanced Filters",
        description = "Scan markets by specific criteria: RSI range, volume spikes, or market cap sectors.",
    ),
    ANALYSIS_ALL_COINS(
        requiredTier = AccessTier.PRO,
        displayName = "Unlimited Technical Scanning",
        description = "Unlocks full technical analysis for all 200+ coins in the terminal database.",
    ),
    CONFIDENCE_METRICS(
        requiredTier = AccessTier.PRO,
        displayName = "Confidence Metrics",
        description = "Detailed breakdown of model agreement scores and underlying data quality.",
    ),
    PREDICTION_HISTORY(
        requiredTier = AccessTier.PRO,
        displayName = "Prediction History",
        description = "A transparent audit log of past AI accuracy for every forecasting engine.",
    ),
    MULTI_TIMEFRAME(
        requiredTier = AccessTier.PRO,
        displayName = "Confluence Analyzer",
        description = "Overview of trend bias across 1H, 4H, and Daily timeframes to find structural alignment.",
    ),
    BACKTESTER(
        requiredTier = AccessTier.PRO,
        displayName = "Strategy Simulator",
        description = "Test trading theories on historical data to validate win rates and profit factors.",
    ),
    ENTRY_QUALITY_SCORER(
        requiredTier = AccessTier.PRO,
        displayName = "Setup Auditor",
        description = "An objective 0-100 rating of your setup based on RSI, Bollinger bands, and funding.",
    ),
    RISK_SCORING(
        requiredTier = AccessTier.PRO,
        displayName = "Systemic Risk Matrix",
        description = "Risk assessment for individual assets based on volatility and liquidity depth.",
    ),
    CORRELATION_MATRIX(
        requiredTier = AccessTier.PRO,
        displayName = "Alpha Correlation Matrix",
        description = "Identify which assets move in lockstep and which show decoupled alpha.",
    ),
    PSYCHOLOGY_LOCK(
        requiredTier = AccessTier.PRO,
        displayName = "Tilt Protection",
        description = "Terminal lock that prevents revenge trading during high market volatility.",
    ),
    STRATEGY_LIBRARY(
        requiredTier = AccessTier.PRO,
        displayName = "Strategy Library",
        description = "Save and manage custom trading strategies and indicator configurations.",
    ),
    TRADE_JOURNAL_UNLIMITED(
        requiredTier = AccessTier.PRO,
        displayName = "Master Trade Ledger",
        description = "A professional performance diary with automated P&L and bias detection.",
    ),
    DEFI_YIELDS(
        requiredTier = AccessTier.PRO,
        displayName = "DeFi Alpha Scanner",
        description = "Real-time monitoring of yields and TVL across major protocols via DefiLlama.",
    ),
    DERIVATIVES_DATA(
        requiredTier = AccessTier.PRO,
        displayName = "Derivatives Intelligence",
        description = "Access Binance futures data: Funding Rates, Open Interest, and L/S ratios.",
    ),
    MACRO_INDICATORS(
        requiredTier = AccessTier.PRO,
        displayName = "Macro Gravity",
        description = "Correlation tracking between crypto and global indices like S&P 500 and DXY.",
    ),
    SEASONAL_PATTERNS(
        requiredTier = AccessTier.PRO,
        displayName = "Cycle Chronology",
        description = "Analysis of historical price patterns by month and major halving cycles.",
    ),
    COMPARISON_TOOL(
        requiredTier = AccessTier.PRO,
        displayName = "Asset Comparison",
        description = "Side-by-side technical and fundamental analysis of any two cryptocurrencies.",
    ),
    CALENDAR(
        requiredTier = AccessTier.PRO,
        displayName = "Crypto Calendar",
        description = "Upcoming forks, listings, and macro-economic events that impact volatility.",
    ),
    DAILY_BRIEFING(
        requiredTier = AccessTier.PRO,
        displayName = "Executive Briefing",
        description = "A comprehensive daily market digest with top trends and high-conviction zones.",
    ),
    ORACLE_DEEP_MODE(
        requiredTier = AccessTier.PRO,
        displayName = "Oracle Deep Reasoning",
        description = "Extended AI analysis with cross-engine reasoning and multi-pillar evidence chains.",
    ),
    PORTFOLIO_TRACKER_FULL(
        requiredTier = AccessTier.PRO,
        displayName = "Portfolio Tracker",
        description = "Live tracking of holdings across multiple chains with aggregated P&L metrics.",
    ),
    ALERTS_UNLIMITED(
        requiredTier = AccessTier.PRO,
        displayName = "Surveillance Grid",
        description = "No limits on active alert counts across any asset or timeframe.",
    ),
    COMPOSITE_ALERTS(
        requiredTier = AccessTier.PRO,
        displayName = "Composite Alerts",
        description = "Combine multiple conditions (Price AND RSI) with Boolean logic.",
    ),
    WHALE_ALERTS(
        requiredTier = AccessTier.PRO,
        displayName = "Whale Proximity Alerts",
        description = "Notifications when specific known institutional wallets move capital.",
    ),
    ACHIEVEMENTS(
        requiredTier = AccessTier.PRO,
        displayName = "Discipline Badges",
        description = "Gamified tracking system for professional trading behavior and risk management.",
    ),
    
    // 🛡️ ADMIN-ONLY FEATURES
    
    PREDICTION_ENGINES_6(
        requiredTier = AccessTier.ADMIN,
        displayName = "Quantum Oracle Ensemble",
        description = "Our most advanced predictive layer running 6 independent statistical models.",
    ),
    CONTENT_STUDIO(
        requiredTier = AccessTier.ADMIN,
        displayName = "Proprietary Content Studio",
        description = "AI-powered marketing and report generation suite for terminal operators.",
    ),
    BYPASS_PAYWALL(
        requiredTier = AccessTier.ADMIN,
        displayName = "System Bypass Protocol",
        description = "Administrative toggle to bypass subscription gates for audits.",
    ),
    DEMO_MODE_MANUAL(
        requiredTier = AccessTier.ADMIN,
        displayName = "Demo Mode Toggle",
        description = "Force synthetic market data for presentations and system demonstrations.",
    ),
    DEBUG_LOGS(
        requiredTier = AccessTier.ADMIN,
        displayName = "Technical Debug Stream",
        description = "Direct access to network and database logs for system maintenance.",
    ),
    SCREENSHOT_MODE(
        requiredTier = AccessTier.ADMIN,
        displayName = "Clean Screenshot UI",
        description = "Hides sensitive or noisy UI elements for professional asset creation.",
    );
    
    companion object {
        fun availableAt(tier: AccessTier): List<FeatureKey> {
            return entries.filter { tier.canAccess(it.requiredTier) }
        }
        fun freeFeatures(): List<FeatureKey> = entries.filter { it.requiredTier == AccessTier.FREE }
        fun proFeatures(): List<FeatureKey> = entries.filter { it.requiredTier == AccessTier.PRO }
        fun adminFeatures(): List<FeatureKey> = entries.filter { it.requiredTier == AccessTier.ADMIN }
    }
}
