package com.cryptodept.viewmodel

enum class TutorialStep(val text: String) {
    WELCOME("INITIALIZING GUIDED ACCESS... WELCOME TO THE ELITE CRYPTO TERMINAL. I WILL GUIDE YOU THROUGH THE CORE SYSTEMS."),
    HEADER("THE SYSTEM STATUS LINE. TAP HERE TO ACCESS GLOBAL NEWS OR VIEW SYSTEM VERSION INFO."),
    WHATS_NEXT("THE AI ORACLE. CLICK '[WHAT NOW?]' FOR REAL-TIME STRATEGIC ADVICE BASED ON CURRENT VOLATILITY."),
    NETWORK_HEALTH("THE NETWORK HEALTH PANEL. MONITORS HASHRATE, GAS, AND THE FEAR/GREED INDEX TO GAUGE MARKET VITALITY."),
    AI_NARRATIVE("AI MARKET NARRATIVE. OUR ENSEMBLE ENGINE COMBINES TA, ON-CHAIN, AND SENTIMENT INTO A SINGLE COHERENT ANALYSIS."),
    COMMAND_BAR("THE COMMAND TERMINAL. TYPE COMMANDS LIKE 'CHART BTC' OR 'RISK' TO NAVIGATE THE SYSTEM WITH SPEED."),
    FINISHED("TUTORIAL COMPLETE. YOU ARE NOW READY TO OPERATE THE TERMINAL. GOOD LUCK, OPERATOR.")
}
